org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Minecraft
minecraft_version=1.21.1
minecraft_version_range=1.21.1

# Fabric
loader_version=0.19.5
loader_version_range=>=0.16.0
loom_version=1.17.21
fabric_api_version=0.116.17+1.21.1

# Mod
mod_id=acceleratedrecoiling
mod_name=AcceleratedRecoiling
mod_license=MIT License
mod_version=21.1.14-fabric
mod_group_id=com.wiyuka
mod_authors=wiyuka
mod_description=A mod of aabb collision optimization
cpp_toolchain_version=toolchain_20261001_0
